### ISSUE TITLE
Unable to build for iOS.

### ISSUE THREAD

**Issue by jasxir** [kineapps/flutter_file_dialog#10]
Hi, I'm getting the following error while building for iOS.

`flutter_file_dialog` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Thanks in advance.

**Comment by kinex** [comment]
Do you still have this issue?

**Comment by JonasKuschel** [comment]
Once I add the package in my pubspec.yaml and try using the package as suggested in the example code I can not build the iOS application anymore.


flutter doctor -v   
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale de-DE)
    • Flutter version 2.0.5 at /Users/jonaskuschel/Developer/flutter
    • Framework revision adc687823a (vor 3 Wochen), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/jonaskuschel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Jonas iPhone (mobile)      • 492883deb15509712e3e8e95d2de5b38ffdfba59 • ios            • iOS 14.4.2
    • iPhone 12 Pro Max (mobile) • 52509AC6-4638-4FE5-93F1-D6093603ED3E     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
jonaskuschel@MacBook-Pro-5 NoWaiter % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale de-DE)
    • Flutter version 2.0.5 at /Users/jonaskuschel/Developer/flutter
    • Framework revision adc687823a (vor 3 Wochen), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/jonaskuschel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 52509AC6-4638-4FE5-93F1-D6093603ED3E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93

**Comment by kinex** [comment]
What is the error message? Is your minimum iOS version 11 or later?

**Comment by JonasKuschel** [comment]
I didn't touch it for a couple days but I think I have switched the iOS version during that time to 11 so that might have been the issue for me. Now it is working fine. Thank you a lot.

**Comment by kinex** [comment]
Ok, thanks. Please reopen if needed.

**Comment by svprdga** [comment]
Hello, 

I suggest to add this information to the README.md since flutter by default creates a project with version 9 and can cause confusion to new users (I had the same error until I found this thread).

So I would add to set a minimum of version 11 in Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'
```

**Comment by kinex** [comment]
Have you read the README.md ? :)
