### ISSUE TITLE
GoogleDrive saveFile on iOS returns null filename 

### ISSUE THREAD

**Issue by aleripe** [kineapps/flutter_file_dialog#16]
```
/// Displays a dialog for selecting a location where to save the file and
/// saves the file to the selected location.
///
/// Returns path of the saved file or null if operation was cancelled.
/// Throws exception on error.
static Future<String?> saveFile({SaveFileDialogParams? params}) {
  return _channel.invokeMethod('saveFile', params?.toJson());
}
```

Documentation of `saveFile` method says that it returns path of the saved file or null if operation was cancelled. However on iOS, saving a file on Google Drive returns null instead of the filename. Can you check it?

Cheers!

**Comment by kinex** [comment]
This looks like an issue in the Drive app. When you save the file, the wrong callback `documentPickerWasCancelled` gets called and this error is shown in log:
`[UIDocumentLog] UIDocumentPickerViewController : didPickDocumentURLs called with nil or 0 URLS`

**Comment by kinex** [comment]
Not an issue in this plugin.
