### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/proguard/coroutines.pro'

### ISSUE THREAD

**Issue by cormalenv** [kineapps/flutter_file_dialog#2]
**_More than one file was found with OS independent path 'META-INF/proguard/coroutines.pro'_** error on dependency add and run without additional code.

Temporary fix applied to build.gradle
// Temporary fix
packagingOptions {
    exclude 'META-INF/proguard/coroutines.pro'
 }

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.476], locale en-AU)
    • Flutter version 1.12.13+hotfix.8 at ...
    • Framework revision 0b8abb4724 (10 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at ...
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi 6 • 672382f37d26 • android-arm • Android 8.1.0 (API 27)

• No issues found!

**Comment by kinex** [comment]
Do you think this issue is caused directly by this plugin? Sounds more like a Gradle or ProGuard configuration issue. To investigate this, I would need a complete project to reproduce it.

**Comment by cormalenv** [comment]
@kinex. A bit beyond me unfortunately. The creators of workmanager listed similar as an issue that required a plugin modification. See [here ](https://stackoverflow.com/questions/52518378/more-than-one-file-was-found-with-os-independent-path-meta-inf-proguard-android). If you have no luck I'll link to a project in the next few days.

**Comment by kinex** [comment]
Thanks for the link. Strange that this does not occur in my app project. I will see this closer when I have time. I guess this is not urgent as you already found a workaround.

**Comment by kinex** [comment]
Is your project using R8 or ProGuard?

**Comment by cormalenv** [comment]
R8, but I just created a fresh project to send to you for testing using 0.0.5 and I can no longer replicate the issue. I'll close this for now and come back to you with more details if it pops up later. Thanks @kinex.

**Comment by kinex** [comment]
Ok. Not sure if there could be this kind of issue if some other plugin in your app depends on a different version of the `coroutines` than this plugin. I am using the latest (or at least very recent) version of it. But let me know if you see this issue again. Thanks!
