### ISSUE TITLE
SaveFileDialogParams : saving a .zip file on GoogleDrive works but file is not recognized as an archive

### ISSUE THREAD

**Issue by deacon78** [kineapps/flutter_file_dialog#21]
Hello

First, thank you for "flutter_file_dialog" !
I have implemented the method "SaveFileDialogParams" on my app.
I want to save a .zip file.
On iOS, on iCLOUD, it works fine.

On GoogleDrive it works but file is not recognized as an archive.

Can you check that please ?

Thank you in advance

Vincent

**Comment by kinex** [comment]
Are you sure the issue is related to this plugin?

**Comment by kinex** [comment]
This is not related to this plugin.
