### ISSUE TITLE
Saving file does not overwrite existing unless selected

### ISSUE THREAD

**Issue by jasonkaruza** [kineapps/flutter_file_dialog#27]
Version 2.1.1

Here is my code to open the Save File Dialog:
```
final params = SaveFileDialogParams(
          data: encoder.convert(data),
          localOnly: true,
          fileName: "default_backup.json");
      String result = await FlutterFileDialog.saveFile(params: params);
```

The dialog opens and prepopulates with suggested file name "default_backup.json". The file already exists, so the expected behavior is that I would be prompted to overwrite the existing file, yes or no. However, it actually saves a new file called "default_backup.json (1)".

This is NOT the case if I select the file with the name "default_backup.json" from within the Save File Dialog, though. When the Save File Dialog opens, if I navigate to the "default_backup.json" file and click on it, then hit Save, I am prompted to overwrite the existing file, yes or no. I would expect that the latter behavior would also be default when not clicking on the file to overwrite explicitly.

**Comment by kinex** [comment]
This happens in Android I guess? See https://developer.android.com/training/data-storage/shared/documents-files#create-file

It states:
ACTION_CREATE_DOCUMENT cannot overwrite an existing file. If your app tries to save a file with the same name, the system appends a number in parentheses at the end of the file name.

So I guess there is nothing we can do to change this behaviour.

**Comment by Stavarmath** [comment]
Hi Kinex,

I just cross checked the Android document. If the file exist then the new file would have an appended text like "(1)" in its **name**. The plugin however is actually adding "(1)" characters to the **file extension** and then the file extension becomes unknow and the file fails to open. Attached screen shot below.

 
<img width="316" alt="Screenshot 2022-11-13 at 3 41 50 PM" src="https://user-images.githubusercontent.com/11497087/201516610-c098e966-b3e9-4d93-90aa-db138c3c5e3c.png">

**Comment by BitBlueDevStudio** [comment]
Why is this closed actually??
This is real bug, and if I implement saving file on native android, there is NO issue like this!

**Comment by BitBlueDevStudio** [comment]
@Stavarmath the fix is just fork this plugin and in FIleDialog.kt remove this line
`applyMimeTypesFilterToIntent(mimeTypesFilter, intent)`

to setting your mime type hardcoded:
` intent.type = "audio/mpeg"`
