### ISSUE TITLE
Extra content being saved to end of file sometimes

### ISSUE THREAD

**Issue by jasonkaruza** [kineapps/flutter_file_dialog#28]
Flutter version: Channel stable, 2.2.2
Flutter File Dialog Version: 2.1.1

```
String data = 'DcniWweTDQU=fM23+7wcDyCSjUpIgWf2Xb6EQr6lDj8pg6WxkjnwbJGqnAAn0VtfQk6OGJTiaJ7tCXYN5H8Woofmhjqmfdg8s88YIcbD3+SG3mILaJA18nh7Ermu28LOAoeARC8a7tyT4GjtnxrVw5YMSZfwnwi/k4g3TWAYckDqowRKhs9ZH+9CDZCIkfZ673ZnUlyjo7sn8YxCuKkKnQcT0PU028JOXwQBsvBEMeHpdYdQfrHokWplbTP/wU6SZ8OOD4dUp5O6q/jOpPBI79+O80jxmbVe3JuSTnEJQNgRVEyEjdBLVMZTRt/OSPBUncMmshJY5MxUSNSpbCetgz/8LtqUwuvBK3YAQOKZIT5gt2wRomwztJCb8THke7YaPmpKnXWytJO0cb0r5wj59DZizxloZQN00e+wJuuqDiwC3uKYoal3x/LhMBZ0ilBkXfCd2CMCBiR78XJritJoMYYqQHw5hr54DnL/66/ag/JKU91HUKzOd7xxAFMK+Meep8cClf5wmYjclyAVtARZRMn6kwpWTtaPrH9wAotgVLnki8JDbLiVFcoaxCZVipbhpmoeCD+c0CTJ/+bS2WxQEGLjd+RtQWJgX8roDa5QNgvYBmVXiNFGBJXvc5FgSJJ9jDoD8mRdID34jeRFWqBM11MzqG5jPT7GdI2iOCFPFYZzlt4hpnhWxa0bT2Q5W3KiV4LLjnoWTv4ZB8TL3IcIuUjiaUpFK8hrjQcmDDriPRKqyqUAfgkcLn+UUx6Vrbd65UB7o6POczwf5/VQnyitHqDSU0RMfRBowKGQdFLXYEb7ql+FkPMKBoSmQQSbyIV9zMFXV89tqNMLDJoQQ4OdqyU1wgqinLGbvkzIBUcInOefqGhlxU3l9givXWYSTWLmwhiIU/bR7o4w8FhsO+otLTwqvZUHVgwJAI88hCxEjekt+4s7azmp3z4jNzfzZTh4rVeaa8ye7YY='; // Set to an encrypted string value
final params = SaveFileDialogParams(
          data: encoder.convert(data),
          localOnly: true,
          fileName: "default_filename.json");
```

In the file selection dialog, I pick the file to save (overwriting existing file in my case) and expect that the data value alone is written to the file. Instead, an extra string is appended to the end:
`GQN64bdtv84fFbW17ic6P2uOQTO4pnDz5nrlATkUMVzgbnKR+nDJQAzxhGKW3OGzIyD1JbgIWH4n2R/1IeNxvM2b/M1mZqBmakDBagYFoYK2OS1xGMThYgY=`

If data is a different value, but the same length, this happens consistently. However, using a longer value the extra content is not appended. Again, the same code path is being executed on the same output file, but if the data being written is a different size (or maybe because it ends in "="?) it is being appended to with the extra string above. Any idea why?

**Comment by kinex** [comment]
In your code sample you are making some encoding for the data. The issue is most probably related to your own code. Please reopen with a full code sample and OS version information if you still think the issue is related to this plugin.

**Comment by hygehyge** [comment]
I found [this](https://stackoverflow.com/questions/56902845/how-to-properly-overwrite-content-of-file-using-android-storage-access-framework) on stackoverflow.
Maybe you have to call `output.channel.truncate(0)` before you write to output.

**Comment by hygehyge** [comment]
I have created [PR](#34 ).
Please review, thanks.

**Comment by kinex** [comment]
@hygehyge Thanks for the fix!

**Comment by hygehyge** [comment]
@kinex Thanks for quick release!
