### ISSUE TITLE
Implemented get absolute path for Android using PickiT library

### ISSUE THREAD

**Issue by selankon** [kineapps/flutter_file_dialog#29]
Hi,

We were facing a big problem related of how to get the absolute path of a file on Android devices. Actually, there is not a official API method to do that. Finally, we discovered [PickiT](https://github.com/HBiSoft/PickiT/) library, that implement necessary code to get an absolute path from an Uri. 

To use it in our project, we forked this repository and implemented necessary methods on this MR (on Gitlab by the moment):

https://gitlab.com/elRepo.io/flutter_file_dialog_pickit/-/merge_requests/1

The related changes are described on the MR description. 

I think that for the moment is the only flutter plugin with this capacities, should we merge it here?

**Comment by kinex** [comment]
This sounds like a feature not needed by most users and not directly related to the purpose of this plugin. I suggest you create a separate Flutter plugin for PickiT, it doesn't have to be part of this plugin.
