### ISSUE TITLE
Android: Only download or recent available as targets for save

### ISSUE THREAD

**Issue by svobost** [kineapps/flutter_file_dialog#37]
Hi guys, 

I guess there must be some simple issue. 
But when I run the `FlutterFileDialog.saveFile` I get only Download and Recent as possible targets for my file. 
What I need to do in otder to access other locations?

**Comment by kinex** [comment]
I think you must have Google Drive app installed to see Google Drive. Also make sure you have the latest version of it installed.

**Comment by svobost** [comment]
@kinex I believe I do not understand. How can Google drive help me to see local folders? 
I can not navigate local folders and select ... anything...

**Comment by kinex** [comment]
In that case I have no idea. In my test device (Android 12) the dialog shows multiple local folders.

**Comment by svobost** [comment]
Thanks anyway... So I will hope that it will be better on other devices. :)

**Comment by kinex** [comment]
Please check if there is a related permission effecting this. Please reopen if you think the issue is related to this plugin.
