### ISSUE TITLE
Library is not Compatible with MinSDK < 19

### ISSUE THREAD

**Issue by manglide** [kineapps/flutter_file_dialog#4]
My App MinSDK is set to 16. During compile, i got 

`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_file_dialog] 
 /build/flutter_file_dialog/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16`

I guess the library is not compatible with SDKs lesser than 19

**Comment by kinex** [comment]
Yes 19 is the minimum version. It is required by ACTION_CREATE_DOCUMENT (https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT)
