### ISSUE TITLE
How to get the path + filename selected by the user before save the file?

### ISSUE THREAD

**Issue by daybson** [kineapps/flutter_file_dialog#6]
@kineapps
This is making no sense to me: I need to save the file beforehand I open the dialog which allows the user to save the file? What?

```
//DETERMINE THE INITIAL DIRECTORY
Directory directory;
if (GetPlatform.isAndroid) {
   directory = await getExternalStorageDirectory();
} else if (GetPlatform.isIOS) {
   directory = await getApplicationDocumentsDirectory();
}

var params = SaveFileDialogParams(sourceFilePath: directory.path);
var savedPath = await FlutterFileDialog.saveFile(params: params);

//IF USER DIDN'T CANCEL, SAVE A FILE WHERE HIM CHOOSED WITH THE FILENAME RETURNED
if (savedPath != null) {
  File file = File(savedPath);
  await file.writeAsBytes(value);
}
```

Throws:

`PlatformException (PlatformException(save_file_failed, /storage/emulated/0/Android/data/com.myapp.app/files (Is a directory), java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.myapp.app/files (Is a directory)))`

Off course is a directory, I'm passing the directory and expecting the return of FlutterFileDialog.saveFile with the full path including the name of the file which the user choosed. 

But then I also tried:
```
Directory directory;

if (GetPlatform.isAndroid) {
  directory = await getExternalStorageDirectory();
} else if (GetPlatform.isIOS) {
  directory = await getApplicationDocumentsDirectory();
}
//SET A INITIAL FILENAME ATTACHED TO THE INITIAL PATH
var fullPath = join(directory.path, 'bkp.txt');

var params = SaveFileDialogParams(sourceFilePath: fullPath);
var savedPath = await FlutterFileDialog.saveFile(params: params);
if (savedPath != null) {
  File file = File(savedPath);
  await file.writeAsBytes(value);
}
```

Throws:
`PlatformException (PlatformException(file_not_found, Source file is missing, /storage/emulated/0/Android/data/com.myapp.app/files/bkp.txt))`

How should I get the path + filename the user selected from the savedialog, when the dialog forces me to create the file beforehand? This is making no sense to me. What am I doing wrong here?

**Comment by Tealokeo** [comment]
This was confusing to me at first as well, but it turned out to be exactly what I needed because it allowed me to save to a much wider range of folders like an Android SD card without requiring complex permissions.

What worked for me was saving a temporary file that the application could access, and then feeding that file path to the SaveFileDialogParams function which then allowed me to save it to folders all over the device.

**Comment by kinex** [comment]
Yes I understand this is slightly confusing. The basic idea is that you have a local file which you want to save to a cloud service like iCloud or Google Drive. Maybe better terms would be `ExportFileDialogParams` and `exportFile`. On the other hand, I could add there in future a new API accepting raw file data directly without need to create a local temp file first. But for now you need to create a local temp file first. You can delete the temp file after it has been saved by this plugin.

So to fix your code, save data to a local temp file and after that call `FlutterFileDialog.saveFile` passing there the path of the temp file.
